version: '3.1'
services:
  mysql:
    image: mysql:5.7
    container_name: mimacom-lr-db-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mimacom
      MYSQL_DATABASE: mimacom
      MYSQL_USER: mimacom
      MYSQL_PASSWORD: mimacom
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
